### PR TITLE
bump pybind11 from 2.6.1 to 2.9.2

### PR DESCRIPTION
**Pull request by tigercosmos**
To support the latest APIs.

### CODE REVIEW

**Comment by tigercosmos** [comment]
@yungyuc  I don't know why there is no CI here

**Comment by yungyuc** [comment]
CI run from first-timer contributor needs to get approval from maintainer.

This upgrade is good, but I think we need some context for future documentation (what's new log).  Could you list the syntax you want to enable through the dependency upgrade?  Listing right here in the PR is good.

**Comment by tigercosmos** [comment]
`pybind11::array::view` ([code ref](https://github.com/pybind/pybind11/blob/0964a9093a728dbf67b9b98c6371752b1a346f25/include/pybind11/numpy.h#L946)) has been introcuded in the current version.

**Comment by yungyuc** [comment]
Is 2.9.2 the current version you mentioned?

**Comment by tigercosmos** [comment]
yes

**Pull request merged**
