### PR TITLE
Fix the typo in README.rst

### LINKED ISSUE #411: Typo in README.rst
The subheadings [`Refenreces`](https://github.com/solvcon/modmesh/blob/5cc3cc326ed66b72315f7116ee9f1a34584d69eb/README.rst?plain=1#L28) need fixing.

### PR DESCRIPTION
**Pull request by ThreeMonth03**
This pr is to fix the typo in issue #411.

### CODE REVIEW

**Review by ThreeMonth03 — COMMENTED** [review]
Replace `Refenreces` with `References`.

**Comment by ThreeMonth03** [comment]
> Replace `Refenreces` with `References`.

@yungyuc @tigercosmos , you could review the code when you are available. Thank you very much.

**Comment by yungyuc** [comment]
LGTM!  Thanks.

**Review by tigercosmos — APPROVED** [review]

**Comment by tigercosmos** [comment]
@ThreeMonth03, btw, if you have time, you can try to use some spelling tools to go through the whole code space and see if there are any other typos.

**Pull request merged**
